### ISSUE TITLE
Build error on macOS (ARM): "ld: symbol(s) not found for architecture arm64"

### ISSUE THREAD

**Issue by PaddiM8** [SerenityOS/ladybird#108]
I get this error when I try to build on macOS 12.6.1 on my M1 and have updated the Xcode command line tools to version 14.1.

```
-- The CXX compiler identification is AppleClang 14.0.0.14000029
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The C compiler identification is AppleClang 14.0.0.14000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Removing outdated /Users/paddi/Clones/ladybird/Build/TZDB for version 2022e
-- Downloading file tzdb.tar.gz from https://data.iana.org/time-zones/releases/tzdata2022e.tar.gz
-- Extracting using cmake africa
-- Extracting using cmake antarctica
-- Extracting using cmake asia
-- Extracting using cmake australasia
-- Extracting using cmake backward
-- Extracting using cmake etcetera
-- Extracting using cmake europe
-- Extracting using cmake northamerica
-- Extracting using cmake southamerica
-- Extracting using cmake zone1970.tab
-- Removing outdated /Users/paddi/Clones/ladybird/Build/CLDR for version 42.0.0
-- Downloading file cldr.zip from https://github.com/unicode-org/cldr-json/releases/download/42.0.0/cldr-42.0.0-json-modern.zip
-- Extracting using cmake cldr-bcp47/**
-- Extracting using cmake cldr-core/**
-- Extracting using cmake cldr-dates-modern/**
-- Extracting using cmake cldr-localenames-modern/**
-- Extracting using cmake cldr-misc-modern/**
-- Extracting using cmake cldr-numbers-modern/**
-- Extracting using cmake cldr-units-modern/**
-- Removing outdated /Users/paddi/Clones/ladybird/Build/UCD for version 15.0.0
-- Downloading file UCD.zip from https://www.unicode.org/Public/15.0.0/ucd/UCD.zip
-- Extracting using cmake UnicodeData.txt
-- Extracting using cmake SpecialCasing.txt
-- Extracting using cmake extracted/DerivedGeneralCategory.txt
-- Extracting using cmake PropList.txt
-- Extracting using cmake DerivedCoreProperties.txt
-- Extracting using cmake extracted/DerivedBinaryProperties.txt
-- Extracting using cmake PropertyAliases.txt
-- Extracting using cmake PropertyValueAliases.txt
-- Extracting using cmake NameAliases.txt
-- Extracting using cmake Scripts.txt
-- Extracting using cmake ScriptExtensions.txt
-- Extracting using cmake Blocks.txt
-- Extracting using cmake emoji/emoji-data.txt
-- Extracting using cmake DerivedNormalizationProps.txt
-- Extracting using cmake auxiliary/GraphemeBreakProperty.txt
-- Extracting using cmake auxiliary/WordBreakProperty.txt
-- Extracting using cmake auxiliary/SentenceBreakProperty.txt
-- Downloading file emoji-test.txt from https://unicode.org/Public/emoji/15.0/emoji-test.txt
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE
-- Found OpenGL: /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/System/Library/Frameworks/OpenGL.framework
-- Found WrapOpenGL: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/paddi/Clones/ladybird/Build
[0/2] Re-checking globbed directories...
[2234/2248] Linking CXX executable WebContent/WebContent
FAILED: WebContent/WebContent
: && /Library/Developer/CommandLineTools/usr/bin/c++ -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk -mmacosx-version-min=12.6 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  WebContent/CMakeFiles/WebContent.dir/WebContent_autogen/mocs_compilation.cpp.o WebContent/CMakeFiles/WebContent.dir/__/serenity/Userland/Services/WebContent/ConnectionFromClient.cpp.o WebContent/CMakeFiles/WebContent.dir/__/serenity/Userland/Services/WebContent/ConsoleGlobalObject.cpp.o WebContent/CMakeFiles/WebContent.dir/__/serenity/Userland/Services/WebContent/PageHost.cpp.o WebContent/CMakeFiles/WebContent.dir/__/serenity/Userland/Services/WebContent/WebContentConsoleClient.cpp.o WebContent/CMakeFiles/WebContent.dir/__/EventLoopPluginQt.cpp.o WebContent/CMakeFiles/WebContent.dir/__/FontPluginQt.cpp.o WebContent/CMakeFiles/WebContent.dir/__/ImageCodecPluginLadybird.cpp.o WebContent/CMakeFiles/WebContent.dir/__/RequestManagerQt.cpp.o WebContent/CMakeFiles/WebContent.dir/__/TimerQt.cpp.o WebContent/CMakeFiles/WebContent.dir/__/Utilities.cpp.o WebContent/CMakeFiles/WebContent.dir/__/WebSocketClientManagerLadybird.cpp.o WebContent/CMakeFiles/WebContent.dir/__/WebSocketLadybird.cpp.o WebContent/CMakeFiles/WebContent.dir/main.cpp.o -o WebContent/WebContent  -Wl,-rpath,/Users/paddi/Clones/ladybird/Build/_deps/lagom-build -Wl,-rpath,/Users/paddi/Clones/ladybird/Build/_deps/lagom-build/Userland/Libraries/LibWebSocket -Wl,-rpath,/Users/paddi/Clones/ladybird/Build/_deps/lagom-build/Userland/Libraries/LibWeb -Wl,-rpath,/opt/homebrew/lib -Wl,-rpath,/Users/paddi/Clones/ladybird/Build/_deps/lagom-build/Userland/Libraries/LibGfx -Wl,-rpath,/Users/paddi/Clones/ladybird/Build/_deps/lagom-build/Userland/Libraries/LibIPC -Wl,-rpath,/Users/paddi/Clones/ladybird/Build/_deps/lagom-build/Userland/Libraries/LibCore  _deps/lagom-build/liblagom-webview.0.0.0.dylib  _deps/lagom-build/Userland/Libraries/LibWebSocket/liblagom-websocket.0.0.0.dylib  _deps/lagom-build/Userland/Libraries/LibWeb/liblagom-web.0.0.0.dylib  _deps/lagom-build/Userland/Libraries/LibMain/liblagom-main.a  /opt/homebrew/lib/QtNetwork.framework/Versions/A/QtNetwork  /opt/homebrew/lib/QtGui.framework/Versions/A/QtGui  /opt/homebrew/lib/QtCore.framework/Versions/A/QtCore  -framework IOKit  -framework DiskArbitration  -framework  OpenGL  -framework  AGL  -framework AppKit  -framework ImageIO  -framework Metal  _deps/lagom-build/Userland/Libraries/LibGfx/liblagom-gfx.0.0.0.dylib  _deps/lagom-build/Userland/Libraries/LibIPC/liblagom-ipc.0.0.0.dylib  _deps/lagom-build/Userland/Libraries/LibCore/liblagom-core.0.0.0.dylib && :
Undefined symbols for architecture arm64:
  "JS::HandleImpl::HandleImpl(JS::Cell*)", referenced from:
      WebContent::WebContentConsoleClient::WebContentConsoleClient(JS::Console&, JS::Realm&, WebContent::ConnectionFromClient&) in WebContentConsoleClient.cpp.o
  "JS::HandleImpl::~HandleImpl()", referenced from:
      WebContent::ConnectionFromClient::get_element_property(int, AK::String const&) in ConnectionFromClient.cpp.o
      WebContent::ConnectionFromClient::~ConnectionFromClient() in ConnectionFromClient.cpp.o
      WebContent::WebContentConsoleClient::~WebContentConsoleClient() in ConnectionFromClient.cpp.o
      WebContent::ConsoleGlobalObject::initialize(JS::Realm&) in ConsoleGlobalObject.cpp.o
      WebContent::WebContentConsoleClient::WebContentConsoleClient(JS::Console&, JS::Realm&, WebContent::ConnectionFromClient&) in WebContentConsoleClient.cpp.o
      WebContent::WebContentConsoleClient::~WebContentConsoleClient() in WebContentConsoleClient.cpp.o
  "JS::same_value(JS::Value, JS::Value)", referenced from:
      WebContent::ConsoleGlobalObject::internal_get(JS::PropertyKey const&, JS::Value) const in ConsoleGlobalObject.cpp.o
      WebContent::ConsoleGlobalObject::internal_set(JS::PropertyKey const&, JS::Value, JS::Value) in ConsoleGlobalObject.cpp.o
  "JS::GlobalObject::initialize(JS::Realm&)", referenced from:
      WebContent::ConsoleGlobalObject::initialize(JS::Realm&) in ConsoleGlobalObject.cpp.o
  "JS::GlobalObject::GlobalObject(JS::Realm&)", referenced from:
      WebContent::ConsoleGlobalObject::ConsoleGlobalObject(JS::Realm&, Web::HTML::Window&) in ConsoleGlobalObject.cpp.o
      WebContent::ConsoleGlobalObject::ConsoleGlobalObject(JS::Realm&, Web::HTML::Window&) in ConsoleGlobalObject.cpp.o
  "JS::GlobalObject::~GlobalObject()", referenced from:
      WebContent::ConsoleGlobalObject::~ConsoleGlobalObject() in ConsoleGlobalObject.cpp.o
      WebContent::ConsoleGlobalObject::~ConsoleGlobalObject() in ConsoleGlobalObject.cpp.o
  "JS::MarkupGenerator::html_from_error(JS::Error const&, bool)", referenced from:
      WebContent::WebContentConsoleClient::report_exception(JS::Error const&, bool) in WebContentConsoleClient.cpp.o
  "JS::MarkupGenerator::html_from_value(JS::Value)", referenced from:
      WebContent::WebContentConsoleClient::handle_input(AK::String const&) in WebContentConsoleClient.cpp.o
  "JS::unregister_safe_function_closure(void*, unsigned long)", referenced from:
      JS::SafeFunction<JS::ThrowCompletionOr<JS::Value> (JS::VM&)>::clear(bool) in ConsoleGlobalObject.cpp.o
  "JS::Heap::undefer_gc(AK::Badge<JS::DeferGC>)", referenced from:
      WebContent::WebContentConsoleClient::WebContentConsoleClient(JS::Console&, JS::Realm&, WebContent::ConnectionFromClient&) in WebContentConsoleClient.cpp.o
  "JS::Heap::allocate_cell(unsigned long)", referenced from:
      WebContent::WebContentConsoleClient::WebContentConsoleClient(JS::Console&, JS::Realm&, WebContent::ConnectionFromClient&) in WebContentConsoleClient.cpp.o
  "JS::Heap::collect_garbage(JS::Heap::CollectionType, bool)", referenced from:
      WebContent::ConnectionFromClient::debug_request(AK::String const&, AK::String const&) in ConnectionFromClient.cpp.o
  "JS::Heap::defer_gc(AK::Badge<JS::DeferGC>)", referenced from:
      WebContent::WebContentConsoleClient::WebContentConsoleClient(JS::Console&, JS::Realm&, WebContent::ConnectionFromClient&) in WebContentConsoleClient.cpp.o
  "JS::Object::visit_edges(JS::Cell::Visitor&)", referenced from:
      WebContent::ConsoleGlobalObject::visit_edges(JS::Cell::Visitor&) in ConsoleGlobalObject.cpp.o
  "JS::Object::internal_set(JS::PropertyKey const&, JS::Value, JS::Value)", referenced from:
      WebContent::ConsoleGlobalObject::internal_set(JS::PropertyKey const&, JS::Value, JS::Value) in ConsoleGlobalObject.cpp.o
  "JS::Object::internal_delete(JS::PropertyKey const&)", referenced from:
      WebContent::ConsoleGlobalObject::internal_delete(JS::PropertyKey const&) in ConsoleGlobalObject.cpp.o
  "JS::Object::define_native_accessor(JS::Realm&, JS::PropertyKey const&, JS::SafeFunction<JS::ThrowCompletionOr<JS::Value> (JS::VM&)>, JS::SafeFunction<JS::ThrowCompletionOr<JS::Value> (JS::VM&)>, JS::PropertyAttributes)", referenced from:
      WebContent::ConsoleGlobalObject::initialize(JS::Realm&) in ConsoleGlobalObject.cpp.o
  "JS::Object::internal_prevent_extensions()", referenced from:
      WebContent::ConsoleGlobalObject::internal_prevent_extensions() in ConsoleGlobalObject.cpp.o
  "JS::Object::internal_define_own_property(JS::PropertyKey const&, JS::PropertyDescriptor const&)", referenced from:
      WebContent::ConsoleGlobalObject::internal_define_own_property(JS::PropertyKey const&, JS::PropertyDescriptor const&) in ConsoleGlobalObject.cpp.o
  "JS::ErrorType::NotAnObjectOfType", referenced from:
      WebContent::ConsoleGlobalObject::inspected_node_getter(JS::VM&) in ConsoleGlobalObject.cpp.o
  "JS::TypeError::create(JS::Realm&, AK::String const&)", referenced from:
      JS::Completion JS::VM::throw_completion<JS::TypeError, char const (&) [20]>(JS::ErrorType, char const (&) [20]) in ConsoleGlobalObject.cpp.o
  "JS::Value::to_string_without_side_effects() const", referenced from:
      AK::Formatter<JS::Value, void>::format(AK::FormatBuilder&, JS::Value) in WebContentConsoleClient.cpp.o
  "JS::Value::to_object(JS::VM&) const", referenced from:
      WebContent::ConsoleGlobalObject::inspected_node_getter(JS::VM&) in ConsoleGlobalObject.cpp.o
  "JS::Value::to_string(JS::VM&) const", referenced from:
      WebContent::ConnectionFromClient::get_element_property(int, AK::String const&) in ConnectionFromClient.cpp.o
  "JS::Object::internal_get(JS::PropertyKey const&, JS::Value) const", referenced from:
      WebContent::ConsoleGlobalObject::internal_get(JS::PropertyKey const&, JS::Value) const in ConsoleGlobalObject.cpp.o
  "JS::Object::has_own_property(JS::PropertyKey const&) const", referenced from:
      WebContent::ConsoleGlobalObject::internal_get(JS::PropertyKey const&, JS::Value) const in ConsoleGlobalObject.cpp.o
  "JS::Object::internal_has_property(JS::PropertyKey const&) const", referenced from:
      WebContent::ConsoleGlobalObject::internal_has_property(JS::PropertyKey const&) const in ConsoleGlobalObject.cpp.o
  "JS::Object::internal_is_extensible() const", referenced from:
      WebContent::ConsoleGlobalObject::internal_is_extensible() const in ConsoleGlobalObject.cpp.o
  "JS::Object::internal_get_own_property(JS::PropertyKey const&) const", referenced from:
      WebContent::ConsoleGlobalObject::internal_get_own_property(JS::PropertyKey const&) const in ConsoleGlobalObject.cpp.o
  "JS::Object::internal_get_prototype_of() const", referenced from:
      WebContent::ConsoleGlobalObject::internal_get_prototype_of() const in ConsoleGlobalObject.cpp.o
  "JS::Object::internal_own_property_keys() const", referenced from:
      WebContent::ConsoleGlobalObject::internal_own_property_keys() const in ConsoleGlobalObject.cpp.o
  "JS::Object::get(JS::PropertyKey const&) const", referenced from:
      WebContent::ConnectionFromClient::get_element_property(int, AK::String const&) in ConnectionFromClient.cpp.o
  "JS::Console::output_debug_message(JS::Console::LogLevel, AK::String const&) const", referenced from:
      WebContent::WebContentConsoleClient::printer(JS::Console::LogLevel, AK::Variant<JS::Console::Group, JS::Console::Trace, JS::MarkedVector<JS::Value, 32ul> >) in WebContentConsoleClient.cpp.o
  "typeinfo for JS::GlobalObject", referenced from:
      typeinfo for WebContent::ConsoleGlobalObject in ConsoleGlobalObject.cpp.o
  "typeinfo for JS::Object", referenced from:
      WebContent::ConsoleGlobalObject::inspected_node_getter(JS::VM&) in ConsoleGlobalObject.cpp.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
ninja: Entering directory `Build'
[0/2] Re-checking globbed directories...
[1/16] Linking CXX executable WebContent/WebContent
FAILED: WebContent/WebContent
: && /Library/Developer/CommandLineTools/usr/bin/c++ -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk -mmacosx-version-min=12.6 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  WebContent/CMakeFiles/WebContent.dir/WebContent_autogen/mocs_compilation.cpp.o WebContent/CMakeFiles/WebContent.dir/__/serenity/Userland/Services/WebContent/ConnectionFromClient.cpp.o WebContent/CMakeFiles/WebContent.dir/__/serenity/Userland/Services/WebContent/ConsoleGlobalObject.cpp.o WebContent/CMakeFiles/WebContent.dir/__/serenity/Userland/Services/WebContent/PageHost.cpp.o WebContent/CMakeFiles/WebContent.dir/__/serenity/Userland/Services/WebContent/WebContentConsoleClient.cpp.o WebContent/CMakeFiles/WebContent.dir/__/EventLoopPluginQt.cpp.o WebContent/CMakeFiles/WebContent.dir/__/FontPluginQt.cpp.o WebContent/CMakeFiles/WebContent.dir/__/ImageCodecPluginLadybird.cpp.o WebContent/CMakeFiles/WebContent.dir/__/RequestManagerQt.cpp.o WebContent/CMakeFiles/WebContent.dir/__/TimerQt.cpp.o WebContent/CMakeFiles/WebContent.dir/__/Utilities.cpp.o WebContent/CMakeFiles/WebContent.dir/__/WebSocketClientManagerLadybird.cpp.o WebContent/CMakeFiles/WebContent.dir/__/WebSocketLadybird.cpp.o WebContent/CMakeFiles/WebContent.dir/main.cpp.o -o WebContent/WebContent  -Wl,-rpath,/Users/paddi/Clones/ladybird/Build/_deps/lagom-build -Wl,-rpath,/Users/paddi/Clones/ladybird/Build/_deps/lagom-build/Userland/Libraries/LibWebSocket -Wl,-rpath,/Users/paddi/Clones/ladybird/Build/_deps/lagom-build/Userland/Libraries/LibWeb -Wl,-rpath,/opt/homebrew/lib -Wl,-rpath,/Users/paddi/Clones/ladybird/Build/_deps/lagom-build/Userland/Libraries/LibGfx -Wl,-rpath,/Users/paddi/Clones/ladybird/Build/_deps/lagom-build/Userland/Libraries/LibIPC -Wl,-rpath,/Users/paddi/Clones/ladybird/Build/_deps/lagom-build/Userland/Libraries/LibCore  _deps/lagom-build/liblagom-webview.0.0.0.dylib  _deps/lagom-build/Userland/Libraries/LibWebSocket/liblagom-websocket.0.0.0.dylib  _deps/lagom-build/Userland/Libraries/LibWeb/liblagom-web.0.0.0.dylib  _deps/lagom-build/Userland/Libraries/LibMain/liblagom-main.a  /opt/homebrew/lib/QtNetwork.framework/Versions/A/QtNetwork  /opt/homebrew/lib/QtGui.framework/Versions/A/QtGui  /opt/homebrew/lib/QtCore.framework/Versions/A/QtCore  -framework IOKit  -framework DiskArbitration  -framework  OpenGL  -framework  AGL  -framework AppKit  -framework ImageIO  -framework Metal  _deps/lagom-build/Userland/Libraries/LibGfx/liblagom-gfx.0.0.0.dylib  _deps/lagom-build/Userland/Libraries/LibIPC/liblagom-ipc.0.0.0.dylib  _deps/lagom-build/Userland/Libraries/LibCore/liblagom-core.0.0.0.dylib && :
Undefined symbols for architecture arm64:
  "JS::HandleImpl::HandleImpl(JS::Cell*)", referenced from:
      WebContent::WebContentConsoleClient::WebContentConsoleClient(JS::Console&, JS::Realm&, WebContent::ConnectionFromClient&) in WebContentConsoleClient.cpp.o
  "JS::HandleImpl::~HandleImpl()", referenced from:
      WebContent::ConnectionFromClient::get_element_property(int, AK::String const&) in ConnectionFromClient.cpp.o
      WebContent::ConnectionFromClient::~ConnectionFromClient() in ConnectionFromClient.cpp.o
      WebContent::WebContentConsoleClient::~WebContentConsoleClient() in ConnectionFromClient.cpp.o
      WebContent::ConsoleGlobalObject::initialize(JS::Realm&) in ConsoleGlobalObject.cpp.o
      WebContent::WebContentConsoleClient::WebContentConsoleClient(JS::Console&, JS::Realm&, WebContent::ConnectionFromClient&) in WebContentConsoleClient.cpp.o
      WebContent::WebContentConsoleClient::~WebContentConsoleClient() in WebContentConsoleClient.cpp.o
  "JS::same_value(JS::Value, JS::Value)", referenced from:
      WebContent::ConsoleGlobalObject::internal_get(JS::PropertyKey const&, JS::Value) const in ConsoleGlobalObject.cpp.o
      WebContent::ConsoleGlobalObject::internal_set(JS::PropertyKey const&, JS::Value, JS::Value) in ConsoleGlobalObject.cpp.o
  "JS::GlobalObject::initialize(JS::Realm&)", referenced from:
      WebContent::ConsoleGlobalObject::initialize(JS::Realm&) in ConsoleGlobalObject.cpp.o
  "JS::GlobalObject::GlobalObject(JS::Realm&)", referenced from:
      WebContent::ConsoleGlobalObject::ConsoleGlobalObject(JS::Realm&, Web::HTML::Window&) in ConsoleGlobalObject.cpp.o
      WebContent::ConsoleGlobalObject::ConsoleGlobalObject(JS::Realm&, Web::HTML::Window&) in ConsoleGlobalObject.cpp.o
  "JS::GlobalObject::~GlobalObject()", referenced from:
      WebContent::ConsoleGlobalObject::~ConsoleGlobalObject() in ConsoleGlobalObject.cpp.o
      WebContent::ConsoleGlobalObject::~ConsoleGlobalObject() in ConsoleGlobalObject.cpp.o
  "JS::MarkupGenerator::html_from_error(JS::Error const&, bool)", referenced from:
      WebContent::WebContentConsoleClient::report_exception(JS::Error const&, bool) in WebContentConsoleClient.cpp.o
  "JS::MarkupGenerator::html_from_value(JS::Value)", referenced from:
      WebContent::WebContentConsoleClient::handle_input(AK::String const&) in WebContentConsoleClient.cpp.o
  "JS::unregister_safe_function_closure(void*, unsigned long)", referenced from:
      JS::SafeFunction<JS::ThrowCompletionOr<JS::Value> (JS::VM&)>::clear(bool) in ConsoleGlobalObject.cpp.o
  "JS::Heap::undefer_gc(AK::Badge<JS::DeferGC>)", referenced from:
      WebContent::WebContentConsoleClient::WebContentConsoleClient(JS::Console&, JS::Realm&, WebContent::ConnectionFromClient&) in WebContentConsoleClient.cpp.o
  "JS::Heap::allocate_cell(unsigned long)", referenced from:
      WebContent::WebContentConsoleClient::WebContentConsoleClient(JS::Console&, JS::Realm&, WebContent::ConnectionFromClient&) in WebContentConsoleClient.cpp.o
  "JS::Heap::collect_garbage(JS::Heap::CollectionType, bool)", referenced from:
      WebContent::ConnectionFromClient::debug_request(AK::String const&, AK::String const&) in ConnectionFromClient.cpp.o
  "JS::Heap::defer_gc(AK::Badge<JS::DeferGC>)", referenced from:
      WebContent::WebContentConsoleClient::WebContentConsoleClient(JS::Console&, JS::Realm&, WebContent::ConnectionFromClient&) in WebContentConsoleClient.cpp.o
  "JS::Object::visit_edges(JS::Cell::Visitor&)", referenced from:
      WebContent::ConsoleGlobalObject::visit_edges(JS::Cell::Visitor&) in ConsoleGlobalObject.cpp.o
  "JS::Object::internal_set(JS::PropertyKey const&, JS::Value, JS::Value)", referenced from:
      WebContent::ConsoleGlobalObject::internal_set(JS::PropertyKey const&, JS::Value, JS::Value) in ConsoleGlobalObject.cpp.o
  "JS::Object::internal_delete(JS::PropertyKey const&)", referenced from:
      WebContent::ConsoleGlobalObject::internal_delete(JS::PropertyKey const&) in ConsoleGlobalObject.cpp.o
  "JS::Object::define_native_accessor(JS::Realm&, JS::PropertyKey const&, JS::SafeFunction<JS::ThrowCompletionOr<JS::Value> (JS::VM&)>, JS::SafeFunction<JS::ThrowCompletionOr<JS::Value> (JS::VM&)>, JS::PropertyAttributes)", referenced from:
      WebContent::ConsoleGlobalObject::initialize(JS::Realm&) in ConsoleGlobalObject.cpp.o
  "JS::Object::internal_prevent_extensions()", referenced from:
      WebContent::ConsoleGlobalObject::internal_prevent_extensions() in ConsoleGlobalObject.cpp.o
  "JS::Object::internal_define_own_property(JS::PropertyKey const&, JS::PropertyDescriptor const&)", referenced from:
      WebContent::ConsoleGlobalObject::internal_define_own_property(JS::PropertyKey const&, JS::PropertyDescriptor const&) in ConsoleGlobalObject.cpp.o
  "JS::ErrorType::NotAnObjectOfType", referenced from:
      WebContent::ConsoleGlobalObject::inspected_node_getter(JS::VM&) in ConsoleGlobalObject.cpp.o
  "JS::TypeError::create(JS::Realm&, AK::String const&)", referenced from:
      JS::Completion JS::VM::throw_completion<JS::TypeError, char const (&) [20]>(JS::ErrorType, char const (&) [20]) in ConsoleGlobalObject.cpp.o
  "JS::Value::to_string_without_side_effects() const", referenced from:
      AK::Formatter<JS::Value, void>::format(AK::FormatBuilder&, JS::Value) in WebContentConsoleClient.cpp.o
  "JS::Value::to_object(JS::VM&) const", referenced from:
      WebContent::ConsoleGlobalObject::inspected_node_getter(JS::VM&) in ConsoleGlobalObject.cpp.o
  "JS::Value::to_string(JS::VM&) const", referenced from:
      WebContent::ConnectionFromClient::get_element_property(int, AK::String const&) in ConnectionFromClient.cpp.o
  "JS::Object::internal_get(JS::PropertyKey const&, JS::Value) const", referenced from:
      WebContent::ConsoleGlobalObject::internal_get(JS::PropertyKey const&, JS::Value) const in ConsoleGlobalObject.cpp.o
  "JS::Object::has_own_property(JS::PropertyKey const&) const", referenced from:
      WebContent::ConsoleGlobalObject::internal_get(JS::PropertyKey const&, JS::Value) const in ConsoleGlobalObject.cpp.o
  "JS::Object::internal_has_property(JS::PropertyKey const&) const", referenced from:
      WebContent::ConsoleGlobalObject::internal_has_property(JS::PropertyKey const&) const in ConsoleGlobalObject.cpp.o
  "JS::Object::internal_is_extensible() const", referenced from:
      WebContent::ConsoleGlobalObject::internal_is_extensible() const in ConsoleGlobalObject.cpp.o
  "JS::Object::internal_get_own_property(JS::PropertyKey const&) const", referenced from:
      WebContent::ConsoleGlobalObject::internal_get_own_property(JS::PropertyKey const&) const in ConsoleGlobalObject.cpp.o
  "JS::Object::internal_get_prototype_of() const", referenced from:
      WebContent::ConsoleGlobalObject::internal_get_prototype_of() const in ConsoleGlobalObject.cpp.o
  "JS::Object::internal_own_property_keys() const", referenced from:
      WebContent::ConsoleGlobalObject::internal_own_property_keys() const in ConsoleGlobalObject.cpp.o
  "JS::Object::get(JS::PropertyKey const&) const", referenced from:
      WebContent::ConnectionFromClient::get_element_property(int, AK::String const&) in ConnectionFromClient.cpp.o
  "JS::Console::output_debug_message(JS::Console::LogLevel, AK::String const&) const", referenced from:
      WebContent::WebContentConsoleClient::printer(JS::Console::LogLevel, AK::Variant<JS::Console::Group, JS::Console::Trace, JS::MarkedVector<JS::Value, 32ul> >) in WebContentConsoleClient.cpp.o
  "typeinfo for JS::GlobalObject", referenced from:
      typeinfo for WebContent::ConsoleGlobalObject in ConsoleGlobalObject.cpp.o
  "typeinfo for JS::Object", referenced from:
      WebContent::ConsoleGlobalObject::inspected_node_getter(JS::VM&) in ConsoleGlobalObject.cpp.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```
