### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by Rumpott** [SerenityOS/ladybird#67]
Working with Ubuntu 22.04.1 LTS
done: 
apt install build-essential cmake libgl1-mesa-dev ninja-build qt6-base-dev qt6-tools-dev-tools
apt install qt6-wayland
apt install qt6

"cmake --build Build" fails with this error-message: 
ladybird-master/WebView.cpp:46:10: fatal error: LibWeb/ImageDecoding.h: No such file or directory
   46 | #include <LibWeb/ImageDecoding.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

Any help is welcomed

**Comment by awesomekling** [comment]
Your git clone is out of date, that include statement was removed several days ago. Just `git pull` :)

**Comment by Rumpott** [comment]
correct, now it's working
Thanx
